language: c
dist: trusty
addons:
  apt:
    packages:
      - python-gobject
      - lftp
install:
  - wget https://downloads.sourceforge.net/project/zero-install/0install/2.12.1/0install-linux-x86_64-2.12.1.tar.bz2;
    tar xf 0install-linux-x86_64-2.12.1.tar.bz2;
    ( cd 0install-linux-x86_64-2.12.1 && ./install.sh home )
  - 0install -c add 0compile http://0install.net/2006/interfaces/0compile.xml
  - 0install -c add 0publish http://0install.net/2006/interfaces/0publish
script:
  - eval "$(ssh-agent -s)"
  - gpg --version
  #- gpg-agent -vv --allow-preset-passphrase --no-detach
  #- echo "$GPG_PASSPHRASE" | python2 -c 'import sys, binascii; sys.stdout.write(binascii.b2a_hex(sys.stdin.read().strip()))' | xargs printf "PRESET_PASSPHRASE $GPG_KEY_ID -1 %s\n" | gpg-connect-agent
  - (umask 0077 && echo "$GPG_PASSPHRASE" >passphrase)
  - gpg --passphrase-file passphrase --batch --import "$GPG_KEY_ID.skey"
  - unset GPG_PASSPHRASE
  - git submodule update --remote
  - git config --global url.ssh://git@github.com/.insteadOf http://github.com/
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/
  - cat ~/.gitconfig
  - feed=$(python3 -c 'import configparser;c=configparser.ConfigParser();c.read("0compile.properties");print(c["compile"]["interface"])');
  - echo "$GIT_DEPLOY_KEY" | base64 -d | ssh-add -
  - remote_url="$(git config remote.origin.url)"
  - if ! git clone -b gh-pages $remote_url gh-pages; then
      set -e;
      git clone --no-checkout $remote_url gh-pages;
      ( cd gh-pages;
        git checkout --orphan gh-pages;
        git rm -rf .
      )
    fi
  - bash run-ci.sh
after_success:
  - (cd gh-pages && git push origin gh-pages)
