#!/bin/sh

remote_url="$(git remote get-url origin | sed 's|.*github.com.|git@github.com:|')"
echo "remote_url: $remote_url"

if ! git clone -b gh-pages $remote_url gh-pages; then
  set -e;
  git clone --no-checkout $remote_url gh-pages;
  ( cd gh-pages;
    git checkout --orphan gh-pages;
    git rm -rf .
  )
fi

