#!/bin/sh

f="$1"
old="$2"

if [ -e "$old" ]; then
  sed '/^<!-- Base64 Signature/,/^-->/ d' <"$old" >"$old.nosig"

  if diff -u "$old.nosig" "$f"; then
    echo "Reusing $old (content did not change)"
    mv "$old.nosig" "$f"
    exit 0
  else
    rm "$old.nosig"
  fi
fi

echo "$GPG_PASSPHRASE" >passphrase
unset GPG_PASSPHRASE
eval "$(gpg-agent --batch --enable-ssh-support -s)"
gpg --passphrase-file passphrase --batch --pinentry-mode loopback \
  --import "$GPG_KEY_ID.skey"
gpg --passphrase-file passphrase --batch --pinentry-mode loopback \
  --default-key $GPG_KEY_ID --sign --detach-sign --output "$f.sig" "$f"
printf "<!-- Base64 Signature\n%s\n-->\n" $(base64 -w0 <"$f.sig") >>"$f"
gpg --passphrase-file passphrase --batch --pinentry-mode loopback \
  --armor --output $GPG_KEY_ID.gpg --export $GPG_KEY_ID
rm passphrase
exit 0

